name: Build chip-tool

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Checkout connectedhomeip v1.4.2.0
      uses: actions/checkout@v4
      with:
        repository: project-chip/connectedhomeip
        ref: refs/tags/v1.4.2.0
        path: connectedhomeip

    - name: Install dependencies
      run: |
        brew install python ninja llvm

    - name: Build chip-tool
      run: |
        cd connectedhomeip
        ./scripts/checkout_submodules.py --shallow --platform darwin
        source scripts/activate.sh
        ./scripts/examples/gn_build_example.sh examples/chip-tool out/chip-tool
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: chip-tool
        path: out/chip-tool/chip-tool
