name: Build chip-tool

on:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/build.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set CHIP ref
      run: echo "CHIP_REF=v1.4.2.0" >> $GITHUB_ENV

    - name: Checkout connectedhomeip 
      uses: actions/checkout@v4
      with:
        repository: project-chip/connectedhomeip
        ref: refs/tags/${{ env.CHIP_REF }}
        path: connectedhomeip

    - name: Install dependencies
      run: |
        brew install python ninja llvm

    - name: Build chip-tool
      run: |
        cd connectedhomeip
        ./scripts/checkout_submodules.py --shallow --platform darwin
        source scripts/activate.sh
        ./scripts/examples/gn_build_example.sh examples/chip-tool out/chip-tool
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: chip-tool
        path: connectedhomeip/out/chip-tool/chip-tool

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.CHIP_REF }}
        release_name: Release ${{ env.CHIP_REF }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: connectedhomeip/out/chip-tool/chip-tool
        asset_name: chip-tool
        asset_content_type: application/octet-stream
